// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE798lg90-hzPP2IKXIwC99cPNbzBs6YA',
    appId: '1:544121681773:web:0b041195d70ec816108c64',
    messagingSenderId: '544121681773',
    projectId: 'moviles2-80bf9',
    authDomain: 'moviles2-80bf9.firebaseapp.com',
    storageBucket: 'moviles2-80bf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC3C78zqQ51oCGjJD4afnatLsOzaIWlgc',
    appId: '1:544121681773:android:4454e4446929aa27108c64',
    messagingSenderId: '544121681773',
    projectId: 'moviles2-80bf9',
    storageBucket: 'moviles2-80bf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ryRTGQq0sLKApP6C6pxT-QN5TxHphcg',
    appId: '1:544121681773:ios:74fd49ba66c652de108c64',
    messagingSenderId: '544121681773',
    projectId: 'moviles2-80bf9',
    storageBucket: 'moviles2-80bf9.appspot.com',
    iosBundleId: 'com.example.socialRed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ryRTGQq0sLKApP6C6pxT-QN5TxHphcg',
    appId: '1:544121681773:ios:74fd49ba66c652de108c64',
    messagingSenderId: '544121681773',
    projectId: 'moviles2-80bf9',
    storageBucket: 'moviles2-80bf9.appspot.com',
    iosBundleId: 'com.example.socialRed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE798lg90-hzPP2IKXIwC99cPNbzBs6YA',
    appId: '1:544121681773:web:7e8e6c813563a822108c64',
    messagingSenderId: '544121681773',
    projectId: 'moviles2-80bf9',
    authDomain: 'moviles2-80bf9.firebaseapp.com',
    storageBucket: 'moviles2-80bf9.appspot.com',
  );
}
